# Generated by Django 2.2.16 on 2020-10-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rentu_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentu',
            name='lang',
            field=models.CharField(choices=[('RU', 'Русский'), ('EN', 'English')], default='RU', max_length=20, verbose_name='Язык пользователя.'),
        ),
    ]
